Repository HICC-Bootcamp/2023-forever-VocaAllday, pull requests merged in 2023-01, with the labels that each got.

#4 Feature/2 join
  .idea/.gitignore
  .idea/modules.xml
  .idea/vcs.xml
  .idea/vocaAllday.iml
  vocaAllday/build.gradle
  vocaAllday/src/main/java/forever/vocaAllday/Role.java
  vocaAllday/src/main/java/forever/vocaAllday/config/CustomAuthenticationEntryPoint.java
  vocaAllday/src/main/java/forever/vocaAllday/config/SecurityConfig.java
  vocaAllday/src/main/java/forever/vocaAllday/controller/AccountController.java
  vocaAllday/src/main/java/forever/vocaAllday/controller/MainController.java
  vocaAllday/src/main/java/forever/vocaAllday/dto/MemberFormDto.java
  vocaAllday/src/main/java/forever/vocaAllday/entity/Member.java
  vocaAllday/src/main/java/forever/vocaAllday/repository/MemberRepository.java
  vocaAllday/src/main/java/forever/vocaAllday/service/MemberDetailServiceImpl.java
  vocaAllday/src/main/java/forever/vocaAllday/service/MemberService.java
  vocaAllday/src/main/resources/application.properties
  vocaAllday/src/main/resources/static/css/index.css
  vocaAllday/src/main/resources/static/css/login.css
  vocaAllday/src/main/resources/static/css/makeTest.css
  vocaAllday/src/main/resources/static/css/signin.css
  vocaAllday/src/main/resources/static/img/logo1.png
  vocaAllday/src/main/resources/static/js/index.js
  vocaAllday/src/main/resources/static/js/login.js
  vocaAllday/src/main/resources/static/js/makeTest.js
  vocaAllday/src/main/resources/static/js/signin.js
  vocaAllday/src/main/resources/templates/index/index.html
  vocaAllday/src/main/resources/templates/login/login.html
  vocaAllday/src/main/resources/templates/makeTest/makeTest.html
  vocaAllday/src/main/resources/templates/signin/signin.html
Labels: feature

#5 feature/3_inputInfo
  vocaAllday/build.gradle
  vocaAllday/src/main/java/forever/vocaAllday/TestInfo.java
  vocaAllday/src/main/java/forever/vocaAllday/config/SecurityConfig.java
  vocaAllday/src/main/java/forever/vocaAllday/controller/AccountController.java
  vocaAllday/src/main/java/forever/vocaAllday/controller/InputInfoController.java
  vocaAllday/src/main/java/forever/vocaAllday/controller/MainController.java
  vocaAllday/src/main/java/forever/vocaAllday/dto/InputVocaDto.java
  vocaAllday/src/main/java/forever/vocaAllday/dto/WrongVocaDto.java
  vocaAllday/src/main/java/forever/vocaAllday/entity/InputVoca.java
  vocaAllday/src/main/java/forever/vocaAllday/entity/Report.java
  vocaAllday/src/main/java/forever/vocaAllday/entity/WrongVoca.java
  vocaAllday/src/main/java/forever/vocaAllday/enums/TestType.java
  vocaAllday/src/main/java/forever/vocaAllday/repository/InputVocaRepository.java
  vocaAllday/src/main/java/forever/vocaAllday/repository/ReportRepository.java
  vocaAllday/src/main/java/forever/vocaAllday/repository/WrongVocaRepository.java
  vocaAllday/src/main/java/forever/vocaAllday/service/ReportService.java
  vocaAllday/src/main/resources/application.properties
  vocaAllday/src/main/resources/templates/makeTest/makeTest.html
Labels: feature

#7 Feat #6: 프론트 데이터 가공해 db 저장, dto 정리
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/jpa-buddy.xml
  .idea/misc.xml
  vocaAllday/src/main/java/forever/vocaAllday/controller/InputInfoController.java
  vocaAllday/src/main/java/forever/vocaAllday/dto/InputInfoDto.java
  vocaAllday/src/main/java/forever/vocaAllday/dto/InputVocaDto.java
  vocaAllday/src/main/java/forever/vocaAllday/entity/InputVoca.java
  vocaAllday/src/main/java/forever/vocaAllday/service/ReportService.java
Labels: feature

#10 Fix #6,etc: 오류 수정
  vocaAllday/src/main/java/forever/vocaAllday/entity/InputVoca.java
  vocaAllday/src/main/java/forever/vocaAllday/entity/Member.java
  vocaAllday/src/main/java/forever/vocaAllday/enums/Role.java
  vocaAllday/src/main/java/forever/vocaAllday/service/ReportService.java
Labels: bug

#12 Feature/4_make test
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/uiDesigner.xml
  vocaAllday/src/main/java/forever/vocaAllday/TestInfo.java
  vocaAllday/src/main/java/forever/vocaAllday/controller/ExamController.java
  vocaAllday/src/main/java/forever/vocaAllday/controller/InputInfoController.java
  vocaAllday/src/main/java/forever/vocaAllday/dto/ExamInfoDto.java
  vocaAllday/src/main/java/forever/vocaAllday/dto/InputInfoDto.java
  vocaAllday/src/main/java/forever/vocaAllday/dto/ValueFormDto.java
  vocaAllday/src/main/java/forever/vocaAllday/enums/ExamType.java
  vocaAllday/src/main/java/forever/vocaAllday/repository/MemberRepository.java
  vocaAllday/src/main/java/forever/vocaAllday/repository/ReportRepository.java
  vocaAllday/src/main/java/forever/vocaAllday/service/ExamService.java
Labels: feature

#14 Fix #9: 경로 수정 및 변수 수정
  vocaAllday/src/main/java/forever/vocaAllday/controller/InputInfoController.java
  vocaAllday/src/main/java/forever/vocaAllday/service/ExamService.java
Labels: fix

#16 Feature/5_makeSentence
  vocaAllday/build.gradle
  vocaAllday/src/main/java/forever/vocaAllday/controller/ExamController.java
  vocaAllday/src/main/java/forever/vocaAllday/dto/SentenceInfoDto.java
  vocaAllday/src/main/java/forever/vocaAllday/repository/InputVocaRepository.java
  vocaAllday/src/main/java/forever/vocaAllday/service/CrawlingService.java
Labels: feature
